name: Build Next.js Site

on:
  push:
    branches:
      - main

jobs:
  build-site:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: nextjs-blog

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js Site
        run: npm run build